order/urls.py
from django.urls import path

from . import views as v


app_name = "order"


urlpatterns = [
    # Order ---------------------------------------------------------------------
    path('', v.order_list, name='order_list'),
    path('create/', v.order_create, name='order_create'),
    path('<int:pk>/details/', v.order_details, name='order_details'),
    path('<int:pk>/update/', v.order_update, name='order_update'),
    path('<int:pk>/delete/', v.order_delete, name='order_delete'),
]

product/urls.py
from django.urls import path

from . import views as v


app_name = "product"


urlpatterns = [
    # Unit Measure ------------------------------------------------------------
    path('unitmeasure/', v.unitmeas_list, name='unitmeas_list'),
    path('unitmeasure/create/', v.unitmeas_create, name='unitmeas_create'),
    path('unitmeasure/<int:pk>/update/', v.unitmeas_update, name='unitmeas_update'),
    path('unitmeasure/<int:pk>/delete/', v.unitmeas_delete, name='unitmeas_delete'),

    # Product Category --------------------------------------------------------
    path('category/', v.prodcat_list, name='prodcat_list'),
    path('category/create/', v.prodcat_create, name='prodcat_create'),
    path('category/<int:pk>/update/', v.prodcat_update, name='prodcat_update'),
    path('category/<int:pk>/delete/', v.prodcat_delete, name='prodcat_delete'),

    # Product -----------------------------------------------------------------
    path('', v.product_list, name='product_list'),
    path('create/', v.product_create, name='product_create'),
    path('<int:pk>/details/', v.product_details, name='product_details'),
    path('<int:pk>/update/', v.product_update, name='product_update'),
    path('<int:pk>/delete/', v.product_delete, name='product_delete'),
]

register/urls.py
from django.urls import path

from . import views as v


app_name = "register"


urlpatterns = [
    # Register ----------------------------------------------------------------
    path('', v.register_list, name='register_list'),
    path('create/', v.register_create, name='register_create'),
    path('<int:pk>/details/', v.register_details, name='register_details'),
    path('<int:pk>/update/', v.register_update, name='register_update'),
    path('<int:pk>/delete/', v.register_delete, name='register_delete'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('dashboard/', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),

    path('financial/', include('financial.urls'), name='financial'),
    path('order/', include('order.urls'), name='order'),
    path('product/', include('product.urls'), name='product'),
    path('register/', include('register.urls'), name='register')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

register/models.py
from django.db import models
from django.urls import reverse_lazy as _

from store.constant import STATE_CHOICES
# from django.contrib.localflavor.us.us_states import STATE_CHOICES


class Register(models.Model):	
	name = models.CharField(max_length=200,)
	cell_main = models.CharField(max_length=11, blank = True)
	cell_contact = models.CharField(max_length=11, blank = True)
	email = models.EmailField(max_length=254, blank=True)
	document = models.CharField(max_length=21, blank = True)
	street = models.CharField(max_length=200, blank=True,)
	number = models.CharField(max_length=30,blank=True)
	zipcode = models.CharField(max_length=11,blank=True)
	state = models.CharField(choices = STATE_CHOICES, max_length=2, blank=True)
	city = models.CharField(max_length=100,blank=True)	
	active = models.BooleanField(default=True)
	
	def __str__(self):
		return self.name
	
	def register_gau_detail(self):
		return _('register:register_details', args=[self.pk])

	def register_gau_edit(self):
		return _('register:register_update', args=[self.pk])

	def register_gau_delete(self):
		return _('register:register_delete', args=[self.pk])

register/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy as _

from .models import Register



# Register  ----------------------------------------------------------------
class RegisterList(ListView):
    model = Register
    template_name = "register/registerList.html"

register_list = RegisterList.as_view()


class RegisterCreate(CreateView):
    model = Register
    template_name = "register/registerCreateUpdate.html"
    fields = '__all__'
    success_url = _('register:register_list')

register_create = RegisterCreate.as_view()


class RegisterDetails(DetailView):
    model = Register
    template_name = "register/registerDetails.html"

register_details = RegisterDetails.as_view()


class RegisterUpdate(UpdateView):
    model = Register
    template_name = "register/registerCreateUpdate.html"
    fields = '__all__'
    success_url = _('register:register_list')

register_update = RegisterUpdate.as_view()


class RegisterDelete(DeleteView):
    model = Register
    template_name = "register/registerDelete.html"
    success_url = _('register:register_list')

register_delete = RegisterDelete.as_view()

register/templates/register/registerCreateUpdate.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Register</h5>
        <form class="form-horizontal" action="" method="POST" enctype="">
          {% csrf_token %}
          <div class="row">
            <div class="col-12 col-lg-6">
              <label for="id_name" class="col-form-label">Name</label>
              {{ form.name }}
            </div>
            <div class="col-6 col-lg-4">
              <label for="id_document" class="col-form-label">Document</label>
              {{ form.document }}
            </div>
            <div class="col-6 col-lg-2">
              <legend class="col-form-label">Active</legend>
              <div class="form-check ms-1">
                <input class="form-check-input ps-0" type="checkbox" checked="" name="active" id="id_active">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-6 col-lg-3">
              <label for="id_cell_main" class="col-form-label">Phone</label>
              {{ form.cell_main }}
            </div>
            <div class="col-6 col-lg-3">
              <label for="id_cell_contact" class="col-form-label">Phone2</label>
              {{ form.cell_contact }}
            </div>
            <div class="col-12 col-lg-6">
              <label for="id_email" class="col-form-label">Email</label>
              {{ form.email }}
            </div>
          </div>
          <div class="row">
            <div class="row">
              <div class="col-12 col-lg-6">
                <label for="id_street" class="col-form-label">Street</label>
                {{ form.street }}
              </div>
              <div class="col-4 col-lg-6">
                <label for="id_number" class="col-form-label">Number</label>
                {{ form.number }}
              </div>
              <div class="col-4 col-lg-4">
                <label for="id_zipcode" class="col-form-label">Zipcode</label>
                {{ form.zipcode }}
              </div>
              <div class="col-12 col-lg-6">
                <label for="id_city" class="col-form-label">City</label>
                {{ form.city }}
              </div>
              <div class="col-3 col-lg-2">
                <label for="id_state" class="col-form-label">State</label>
                <select class="form-select" aria-label="Default select example" name="state" id="id_state">
                  {% for item in form.state %}
                  <option>{{ item }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="row my-3">
              <div class="col-sm-12">
                <button type="submit" class="btn btn-primary btn-sm" value="Update">Submit</button>
                <a class="btn btn-danger btn-sm" href="{% url 'register:register_list' %}">Cancel</a>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

register/templates/register/registerDelete.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Delete{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <h5>Delete</h5>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Are you sure you want to delete the record: <b>{{ object.name }}</b>?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-sm">Submit</button>
          <a class="btn btn-danger btn-sm" href="{% url 'product:product_list' %}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</main>
{% endblock %}

register/templates/register/registerDetails.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Details{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Register Details</h5>
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button"
            role="tab" aria-controls="profile" aria-selected="true">Profile</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button"
            role="tab" aria-controls="contact" aria-selected="false" tabindex="-1">Contact</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="adress-tab" data-bs-toggle="tab" data-bs-target="#adress" type="button"
            role="tab" aria-controls="adress" aria-selected="false" tabindex="-1">Adress</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="orders-tab" data-bs-toggle="tab" data-bs-target="#orders" type="button"
            role="tab" aria-controls="orders" aria-selected="false" tabindex="-1">Orders</button>
        </li>
      </ul>
      <div class="tab-content pt-4" id="myTabContent">
        <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          <div class="card mb-1 p-3">
            <p><b>Name: </b> {{ object.name }}</p>
            <p><b>Document: </b> {{ object.document }}</p>
            <p><b>Active: </b> {{ object.active }}</p>
          </div>
        </div>
        <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
          <div class="card mb-1 p-3">
            <p><b>Cell: </b> {{ object.cell_main }}</p>
            <p><b>Phone: </b> {{ object.cell_contact }}</p>
            <p><b>Email: </b> {{ object.email }}</p>
          </div>
        </div>
        <div class="tab-pane fade" id="adress" role="tabpanel" aria-labelledby="adress-tab">
          <div class="card mb-1 p-3">
            <p><b>Street: </b> {{ object.street }}</p>
            <p><b>Number: </b> {{ object.number }}</p>
            <p><b>Zipcode: </b> {{ object.zipcode }}</p>
            <p><b>State: </b> {{ object.state }}</p>
            <p><b>City: </b> {{ object.city }}</p>
          </div>
        </div>
        <div class="tab-pane fade" id="orders" role="tabpanel" aria-labelledby="orders-tab">
          <div class="card mb-1 p-3">
            <p class="">
              Saepe animi et soluta ad odit soluta sunt. Nihil quos omnis animi debitis cumque. Accusantium quibusdam
              perspiciatis qui qui omnis magnam. Officiis accusamus impedit molestias nostrum veniam. Qui amet ipsum
              iure.
              Dignissimos fuga tempore dolor.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

register/templates/register/registerList.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Registers{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="row align-items-center pb-2">
    <div class="col-6">
      <h5 class="">Registers</h5>
    </div>
    <div class="col-6">
      <a class="d-flex float-end" href="{% url 'register:register_create' %}">
        <img src="{% static 'img/plus.png' %}" alt="" width="40" height="40">
      </a>
    </div>
  </div>

  <table class="table table-sm" id="id_table">
    <caption>Registers</caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Cel</th>
        <th scope="col">Email</th>
        <th scope="col">Document</th>
        <th scope="col">Active</th>
        <th scope="col">Edit/Del</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr>
        <td>{{ object.id }}</td>
        <td>
          <a href="{{ object.register_gau_detail }}">{{ object.name }}</a>
        </td>
        <td>{{ object.cell_main }}</td>
        <td>{{ object.email }}</td>
        <td>{{ object.document }}</td>
        {% if object.active %}
        <td><i class="fa fa-check"></i></td>
        {% else %}
        <td><i class="fa fa-close"></i></td>
        {% endif %}
        <td>
          <a class="px-2" href="{{ object.register_gau_edit }}">
            <i class="fa fa-edit"></i>
          </a>
          <a class="px-2" href="{{ object.register_gau_delete }}" style="padding-left: 7px">
            <i class="fa fa-close no"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock dashboard %}