financial/urls.py
from django.urls import path

from . import views as v


app_name = "financial"


urlpatterns = [
    # Bank --------------------------------------------------------------------
    path('banks/', v.bank_list, name='bank_list'),
    path('bank/create/', v.bank_create, name='bank_create'),
    path('bank/<int:pk>/details/', v.bank_details, name='bank_details'),
    path('bank/<int:pk>/update/', v.bank_update, name='bank_update'),
    path('bank/<int:pk>/delete/', v.bank_delete, name='bank_delete'),

    # Account ------------------------------------------------------------------
    path('<bank_id>/account/', v.account_list, name='account_list'),
    path('<bank_id>/account/create/', v.account_create, name='account_create'),
    path('<bank_id>/account/<int:pk>/details/', v.account_details, name='account_details'),
    path('<bank_id>/account/<int:pk>/update/', v.account_update, name='account_update'),
    path('<bank_id>/account/<int:pk>/delete/', v.account_delete, name='account_delete'),

    # Release ------------------------------------------------------------------
    path('release/', v.release_list, name='release_list'),
    path('release/create/', v.release_create, name='release_create'),
    path('release/<int:pk>/details/', v.release_details, name='release_details'),
    path('release/<int:pk>/update/', v.release_update, name='release_update'),
    path('release/<int:pk>/delete/', v.release_delete, name='release_delete'),

    # Destination Category -----------------------------------------------------
    path('destination/category/', v.destcat_list, name='destcat_list'),
    path('destination/category/create/', v.destcat_create, name='destcat_create'),
    path('destination/category/<int:pk>/update/', v.destcat_update, name='destcat_update'),
    path('destination/category/<int:pk>/delete/', v.destcat_delete, name='destcat_delete'),

    # Destination ---------------------------------------------------------------
    path('destination/', v.destination_list, name='destination_list'),
    path('destination/create/', v.destination_create, name='destination_create'),
    path('destination/<int:pk>/update/', v.destination_update, name='destination_update'),
    path('destination/<int:pk>/delete/', v.destination_delete, name='destination_delete'),

    # FormPayment ---------------------------------------------------------------
    path('formpayment/', v.formpayment_list, name='formpayment_list'),
    path('formpayment/create/', v.formpayment_create, name='formpayment_create'),
    path('formpayment/<int:pk>/update/', v.formpayment_update, name='formpayment_update'),
    path('formpayment/<int:pk>/delete/', v.formpayment_delete, name='formpayment_delete'),

    # Payment -------------------------------------------------------------------
    path('payment/', v.payment_list, name='payment_list'),
    path('payment/create/', v.payment_create, name='payment_create'),
    path('payment/<int:pk>/details/', v.payment_details, name='payment_details'),
    path('payment/<int:pk>/update/', v.Payment_update, name='Payment_update'),
    path('payment/<int:pk>/delete/', v.payment_delete, name='payment_delete'),
]

order/urls.py
from django.urls import path

from . import views as v


app_name = "order"


urlpatterns = [
    # Order ---------------------------------------------------------------------
    path('', v.order_list, name='order_list'),
    path('create/', v.order_create, name='order_create'),
    path('<int:pk>/details/', v.order_details, name='order_details'),
    path('<int:pk>/update/', v.order_update, name='order_update'),
    path('<int:pk>/delete/', v.order_delete, name='order_delete'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('dashboard/', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),

    path('financial/', include('financial.urls'), name='financial'),
    path('order/', include('order.urls'), name='order'),
    path('product/', include('product.urls'), name='product'),
    path('register/', include('register.urls'), name='register')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

financial/models.py
from django.db import models
from django.urls.base import reverse_lazy as _

from order.models import Order



class Bank(models.Model):
    name = models.CharField( max_length=50)
    number = models.CharField(max_length=10)
    agency = models.CharField(max_length=8)
    details = models.CharField(max_length=255, null=True, blank=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Bank'
        verbose_name_plural = 'Banks'
        ordering = ['-createdin']

    def __str__(self):
        return self.name

    def bank_gau_detail(self):
        return _('financial:bank_details', args=[self.pk])

    def bank_gau_edit(self):
        return _('financial:bank_update', args=[self.pk])

    def bank_gau_delete(self):
        return _('financial:bank_delete', args=[self.pk])


class Account(models.Model):
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE, related_name='banks')
    name = models.CharField( max_length=50)
    description = models.CharField(max_length=100, blank=True)
    details = models.CharField(max_length=255, null=True, blank=True)
    balance = models.DecimalField(max_digits=12, decimal_places=2, default=0) 
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'
        ordering = ['-createdin']

    def __str__(self):
        return self.name

    # def account_gau_detail(self):
    #     return _('financial:account_details', args=[{'bank_id': self.bank_id},{'pk':self.pk}])

    # def account_gau_edit(self):
    #     return _('financial:account_update', args=[self.pk])

    # def account_gau_delete(self):
    #     return _('financial:account_delete', args=[{'bank_id': self.bank_id},{'pk':self.pk}])


class DestinationCategory(models.Model):
    name = models.CharField(max_length=50)
    details = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.name)

    def destcat_gau_edit(self):
        return _('financial:destcat_update', args=[self.pk])

    def destcat_gau_delete(self):
        return _('financial:destcat_delete', args=[self.pk])

class Destination(models.Model):
    name = models.CharField( max_length=50)
    category = models.ForeignKey(DestinationCategory, on_delete=models.CASCADE)
    details = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.name)

    def dest_gau_edit(self):
        return _('financial:destination_update', args=[self.pk])

    def dest_gau_delete(self):
        return _('financial:destination_delete', args=[self.pk])

class Release(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order')
    date = models.DateField()
    description = models.CharField(max_length=100, blank=True)
    valueorder = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    installments = models.CharField(max_length=2, blank=True)
    totalorder = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    details = models.CharField(max_length=255, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.order)

    def release_gau_edit(self):
        return _('financial:release_update', args=[self.pk])

    def release_gau_delete(self):
        return _('financial:release_delete', args=[self.pk])

    class Meta:
        ordering = ['-createdin']


class FormPayment(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Form Payment'
        verbose_name_plural = 'Forms Payments'

    def __str__(self):
        return self.name

    def formpayment_gau_edit(self):
        return _('financial:Payment_update', args=[self.pk])

    def formpayment_gau_delete(self):
        return _('financial:payment_delete', args=[self.pk])


class Payment(models.Model):
    release = models.ForeignKey(Release, on_delete=models.CASCADE, related_name='release')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='account')
    date = models.DateField()
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, null=True, blank=True)
    value = models.DecimalField(max_digits=11, decimal_places=2)
    details = models.CharField(max_length=255, null=True, blank=True)
    formpayment = models.ForeignKey(FormPayment, on_delete=models.CASCADE, max_length=255)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'
        ordering = ['-createdin']

    def __str__(self):
        return self.name

    def payment_gau_detail(self):
        return _('financial:payment_details', args=[self.pk])

    def payment_gau_edit(self):
        return _('financial:Payment_update', args=[self.pk])

    def payment_gau_delete(self):
        return _('financial:payment_delete', args=[self.pk])

financial/forms.py
from django import forms

from .models import Account


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = '__all__'
        exclude = ('bank',)

financial/templates/financial/release/releaseCreateUpdate.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Release{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Release</h5>
        <form class="form-horizontal" action="" method="POST" enctype="">
          {% csrf_token %}
          <div class="row">
            <div class="col-3 col-lg-3">
              <label for="id_order" class="col-form-label">Order</label>
              <select class="form-select" aria-label="Default select example" name="order" id="id_order">
                {% for item in form.order %}
                <option>{{ item }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-3 col-lg-3">
              <label for="id_date" class="col-form-label">Date</label>
              {{ form.date }}
            </div>
            <div class="col-2 col-lg-2">
              <label for="id_installments" class="col-form-label">Installments</label>
              {{ form.installments }}
            </div>
            <div class="col-2 col-lg-2">
              <label for="id_valueorder" class="col-form-label">Value</label>
              {{ form.valueorder }}
            </div>
            <div class="col-2 col-lg-2">
              <label for="id_totalorder" class="col-form-label">Total</label>
              {{ form.totalorder }}
            </div>
          </div>
          <div class="col-12 col-lg-12">
            <label for="id_description" class="col-form-label">Description</label>
            {{ form.description }}
          </div>
          <div class="col-12 col-lg-12">
            <label for="id_details" class="col-form-label">Details</label>
            {{ form.details }}
          </div>
          <div class="row my-3">
            <div class="col-sm-12">
              <button type="submit" class="btn btn-primary btn-sm" value="Update">Submit</button>
              <a class="btn btn-danger btn-sm" href="{% url 'financial:release_list' %}">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

financial/templates/financial/release/releaseDelete.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Delete{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <h5>Delete</h5>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Are you sure you want to delete the record: <b>{{ object.name }}</b>?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-sm">Submit</button>
          <a class="btn btn-danger btn-sm" href="{% url 'financial:release_list' %}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</main>
{% endblock %}

financial/templates/financial/release/releaseList.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Releases{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="row align-items-center pb-2">
    <div class="col-6">
      <h5 class="">Releases</h5>
    </div>
    <div class="col-6">
      <a class="d-flex float-end" href="{% url 'financial:release_create' %}">
        <img src="{% static 'img/plus.png' %}" alt="" width="40" height="40">
      </a>
    </div>
  </div>

  <table class="table table-sm" id="id_table">
    <caption>Releases</caption>
    <thead>
      <tr>
        <th scope="col">Order</th>
        <th scope="col">Date</th>
        <th scope="col">Description</th>
        <th scope="col">Valueorder</th>
        <th scope="col">Installments</th>
        <th scope="col">Totalorder</th>
        <th scope="col">Details</th>
        <th scope="col">Edit/Del</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr>
        <td>{{ object.order }}</td>
        <td> {{ object.date }}</td>
        <td>{{ object.description }}</td>
        <td>{{ object.valueorder }}</td>
        <td>{{ object.installments }}</td>
        <td>{{ object.totalorder }}</td>
        <td>{{ object.details }}</td>
        <td>
          <a class="px-2" href="{{ object.release_gau_edit }}">
            <i class="fa fa-edit"></i>
          </a>
          <a class="px-2" href="{{ object.release_gau_delete }}" style="padding-left: 7px">
            <i class="fa fa-close no"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock dashboard %}

financial/templates/financial/release/releaseRegisterUpdate.html
<!-- person_form.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Account</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Save</button>
          <a class="btn btn-danger" href="{% url 'financial:account_list' %}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}