order/urls.py
from django.urls import path

from . import views as v


app_name = "order"


urlpatterns = [
    # Order ---------------------------------------------------------------------
    path('', v.order_list, name='order_list'),
    path('create/', v.order_create, name='order_create'),
    path('<int:pk>/details/', v.order_details, name='order_details'),
    path('<int:pk>/update/', v.order_update, name='order_update'),
    path('<int:pk>/delete/', v.order_delete, name='order_delete'),
]

product/urls.py
from django.urls import path

from . import views as v


app_name = "product"


urlpatterns = [
    # Unit Measure ------------------------------------------------------------
    path('unitmeasure/', v.unitmeas_list, name='unitmeas_list'),
    path('unitmeasure/create/', v.unitmeas_create, name='unitmeas_create'),
    path('unitmeasure/<int:pk>/update/', v.unitmeas_update, name='unitmeas_update'),
    path('unitmeasure/<int:pk>/delete/', v.unitmeas_delete, name='unitmeas_delete'),

    # Product Category --------------------------------------------------------
    path('category/', v.prodcat_list, name='prodcat_list'),
    path('category/create/', v.prodcat_create, name='prodcat_create'),
    path('category/<int:pk>/update/', v.prodcat_update, name='prodcat_update'),
    path('category/<int:pk>/delete/', v.prodcat_delete, name='prodcat_delete'),

    # Product -----------------------------------------------------------------
    path('', v.product_list, name='product_list'),
    path('create/', v.product_create, name='product_create'),
    path('<int:pk>/details/', v.product_details, name='product_details'),
    path('<int:pk>/update/', v.product_update, name='product_update'),
    path('<int:pk>/delete/', v.product_delete, name='product_delete'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('dashboard/', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),

    path('financial/', include('financial.urls'), name='financial'),
    path('order/', include('order.urls'), name='order'),
    path('product/', include('product.urls'), name='product'),
    path('register/', include('register.urls'), name='register')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

product/models.py
from django.db import models
from django.urls import reverse_lazy as _



class UnitMeasure(models.Model):
    name = models.CharField( max_length=50)
    abbreviation = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def unit_gau_edit(self):
        return _('product:unit_update', args=[self.pk])

    def unit_gau_delete(self):
        return _('product:unit_delete', args=[self.pk])


class ProductCategory(models.Model):
    name = models.CharField(max_length=50)
    details = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    def prodcat_gau_edit(self):
        return _('product:prodcat_update', args=[self.pk])

    def prodcat_gau_delete(self):
        return _('product:prodcat_delete', args=[self.pk])


class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, blank=True)
    valueBuy = models.DecimalField(max_digits=9, decimal_places=2)
    valueSell = models.DecimalField(max_digits=9, decimal_places=2)
    details = models.CharField(max_length=255, null=True, blank=True)
    stock = models.PositiveIntegerField(default=0)
    available = models.PositiveIntegerField(default=0)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['name']

    def __str__(self):
        return self.name

    def product_gau_detail(self):
        return _('product:product_details', args=[self.pk])

    def product_gau_edit(self):
        return _('product:product_update', args=[self.pk])

    def product_gau_delete(self):
        return _('product:product_delete', args=[self.pk])


    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.name,
            'estoque': self.stock,
        }

product/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy as _

from .models import UnitMeasure, ProductCategory, Product



# Unit Measure ------------------------------------------------------------
class UnitMeasList(ListView):
    model = UnitMeasure
    template_name = "product/others/unitmeasList.html"

unitmeas_list = UnitMeasList.as_view()


class UnitMeasCreate(CreateView):
    model = UnitMeasure
    template_name = "product/others/unitmeasCreateUpdate.html"
    fields = '__all__'
    success_url = _('product:unitmeas_list')

unitmeas_create = UnitMeasCreate.as_view()


class UnitMeasUpdate(UpdateView):
    model = UnitMeasure
    template_name = "product/others/unitmeasCreateUpdate.html"
    fields = '__all__'
    success_url = _('product:unitmeas_list')

unitmeas_update = UnitMeasUpdate.as_view()


class UnitMeasDelete(DeleteView):
    model = UnitMeasure
    template_name = "product/others/unitmeasDelete.html"
    success_url = _('product:unitmeas_list')

unitmeas_delete = UnitMeasDelete.as_view()


# Product Category --------------------------------------------------------
class ProductCategoryList(ListView):
    model = ProductCategory
    template_name = "product/others/prodcatList.html"

prodcat_list = ProductCategoryList.as_view()


class ProductCategoryCreate(CreateView):
    model = ProductCategory
    template_name = "product/others/prodcatCreateUpdate.html"
    fields = '__all__'
    success_url = _('product:prodcat_list')

prodcat_create = ProductCategoryCreate.as_view()


class ProductCategoryUpdate(UpdateView):
    model = ProductCategory
    template_name = "product/others/prodcatCreateUpdate.html"
    fields = '__all__'
    success_url = _('product:prodcat_list')

prodcat_update = ProductCategoryUpdate.as_view()


class ProductCategoryDelete(DeleteView):
    model = ProductCategory
    template_name = "product/others/prodcatDelete.html"
    success_url = _('product:prodcat_list')

prodcat_delete = ProductCategoryDelete.as_view()


# Product  ----------------------------------------------------------------
class ProductList(ListView):
    model = Product
    template_name = "product/productList.html"

product_list = ProductList.as_view()


class ProductCreate(CreateView):
    model = Product
    template_name = "product/productCreateUpdate.html"
    fields = '__all__'
    success_url = _('product:product_list')

product_create = ProductCreate.as_view()


class ProductDetails(DetailView):
    model = Product
    template_name = "product/productDetails.html"

product_details = ProductDetails.as_view()


class ProductUpdate(UpdateView):
    model = Product
    template_name = "product/productCreateUpdate.html"
    fields = '__all__'
    success_url = _('product:product_list')

product_update = ProductUpdate.as_view()


class ProductDelete(DeleteView):
    model = Product
    template_name = "product/productDelete.html"
    success_url = _('product:product_list')

product_delete = ProductDelete.as_view()

product/templates/product/productCreateUpdate.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Product{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Product</h5>
        <form class="form-horizontal" action="" method="POST" enctype="">
          {% csrf_token %}
          <div class="row align-items-center">
            <div class="col-12 col-lg-6">
              <label for="id_name" class="col-form-label">Name</label>
              {{ form.name }}
            </div>
            <div class="col-3 col-lg-3">
              <label for="id_category" class="col-form-label">Category</label>
              <select class="form-select" aria-label="Default select example" name="category" id="id_category">
                {% for item in form.category %}
                <option>{{ item }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-1 col-lg-1 pt-4">
              <a href="{% url 'product:prodcat_create' %}"><i class="fa fa-plus" aria-hidden="true"></i></a>
            </div>
            <div class="col-2 col-lg-2">
              <legend class="col-form-label">Active</legend>
              <div class="form-check ms-1">
                <input class="form-check-input ps-0" type="checkbox" checked="" name="active" id="id_active">
              </div>
            </div>
          </div>
          <div class="col-12">
            <label for="id_description" class="col-form-label">Description</label>
            {{ form.description }}
          </div>
          <div class="row">
            <div class="col-6 col-lg-3">
              <label for="id_valueBuy" class="col-form-label">Value Buy</label>
              {{ form.valueBuy }}
            </div>
            <div class="col-6 col-lg-3">
              <label for="id_valueSell" class="col-form-label">Value Sell</label>
              {{ form.valueSell }}
            </div>
            <div class="col-6 col-lg-3">
              <label for="id_stock" class="col-form-label">Stock</label>
              {{ form.stock }}
            </div>
            <div class="col-6 col-lg-3">
              <label for="id_available" class="col-form-label">available</label>
              {{ form.available }}
            </div>
          </div>
          <div class="col-12 mb-3">
            <label for="id_details" class="col-form-label">Details</label>
            {{ form.details }}
          </div>
          <div class="row my-3">
            <div class="col-sm-12">
              <button type="submit" class="btn btn-primary btn-sm" value="Update">Submit</button>
              <a class="btn btn-danger btn-sm" href="{% url 'product:product_list' %}">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% endblock %}

product/templates/product/productDelete.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Product{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <h5>Delete</h5>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Are you sure you want to delete the record: <b>{{ object.name }}</b>?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-sm">Submit</button>
          <a class="btn btn-danger btn-sm" href="{% url 'product:product_list' %}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</main>
{% endblock %}

product/templates/product/productDetails.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Product Details{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Product Details</h5>
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button"
            role="tab" aria-controls="profile" aria-selected="true">Profile</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="accounting-tab" data-bs-toggle="tab" data-bs-target="#accounting" type="button"
            role="tab" aria-controls="accounting" aria-selected="false" tabindex="-1">Accounting</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="adress-tab" data-bs-toggle="tab" data-bs-target="#adress" type="button"
            role="tab" aria-controls="adress" aria-selected="false" tabindex="-1">Adress</button>
        </li>
      </ul>
      <div class="tab-content pt-4" id="myTabContent">
        <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          <div class="card mb-1 p-3">
            <p><b>Name:</b> {{ object.name }}</p>
            <p><b>Category:</b> {{ object.category}}</p>
            <p><b>Description:</b> {{ object.description }}</p>
            <p><b>Details:</b> {{ object.details }}</p>
          </div>
        </div>
        <div class="tab-pane fade" id="accounting" role="tabpanel" aria-labelledby="accounting-tab">
          <div class="card mb-1 p-3">
            <p><b>Value Buy:</b> $ {{ object.valueBuy }}</p>
            <p><b>Value Sell:</b> $ {{ object.valueSell }}</p>
            <p><b>Stock:</b> {{ object.stock }}</p>
            <p><b>Available:</b> {{ object.available }}</p>
          </div>
        </div>
        <div class="tab-pane fade" id="adress" role="tabpanel" aria-labelledby="adress-tab">
          <div class="card mb-1 p-3">
            <p><b>Active:</b> {{ object.active }}</p>
            <p><b>Updated:</b> {{ object.updated|date:"Y/M/d" }}</p>
            <p><b>Created:</b> {{ object.createdin|date:"Y/M/d" }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

product/templates/product/productList.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Products{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="row align-items-center pb-2">
    <div class="col-6">
      <h5 class="">Products</h5>
    </div>
    <div class="col-6">
      <a class="d-flex float-end" href="{% url 'product:product_create' %}">
        <img src="{% static 'img/plus.png' %}" alt="" width="40" height="40">
      </a>
    </div>
  </div>

  <table class="table table-sm" id="id_table">
    <caption>Products</caption>
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Category</th>
        <th scope="col">Description</th>
        <th scope="col">Value Buy</th>
        <th scope="col">Value Sell</th>
        <th scope="col">Stock</th>
        <th scope="col">Available</th>
        <th scope="col">Active</th>
        <th scope="col">Edit/Del</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr>
        <td>
          <a href="{{ object.product_gau_detail }}">{{ object.name }}</a>
        </td>
        <td>{{ object.category }}</td>
        <td>{{ object.description }}</td>
        <td>{{ object.valueBuy }}</td>
        <td>{{ object.valueSell }}</td>
        <td>{{ object.stock }}</td>
        <td>{{ object.available }}</td>
        {% if object.active %}
        <td><i class="fa fa-check"></i></td>
        {% else %}
        <td><i class="fa fa-close"></i></td>
        {% endif %}
        <td>
          <a class="px-2" href="{{ object.product_gau_edit }}">
            <i class="fa fa-edit"></i>
          </a>
          <a class="px-2" href="{{ object.product_gau_delete }}" style="padding-left: 7px">
            <i class="fa fa-close no"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock %}