financial/urls.py
from django.urls import path

from . import views as v


app_name = "financial"


urlpatterns = [
    # Bank --------------------------------------------------------------------
    path('banks/', v.bank_list, name='bank_list'),
    path('bank/create/', v.bank_create, name='bank_create'),
    path('bank/<int:pk>/details/', v.bank_details, name='bank_details'),
    path('bank/<int:pk>/update/', v.bank_update, name='bank_update'),
    path('bank/<int:pk>/delete/', v.bank_delete, name='bank_delete'),

    # Account ------------------------------------------------------------------
    path('<bank_id>/account/', v.account_list, name='account_list'),
    path('<bank_id>/account/create/', v.account_create, name='account_create'),
    path('<bank_id>/account/<int:pk>/details/', v.account_details, name='account_details'),
    path('<bank_id>/account/<int:pk>/update/', v.account_update, name='account_update'),
    path('<bank_id>/account/<int:pk>/delete/', v.account_delete, name='account_delete'),

    # Release ------------------------------------------------------------------
    path('release/', v.release_list, name='release_list'),
    path('release/create/', v.release_create, name='release_create'),
    path('release/<int:pk>/details/', v.release_details, name='release_details'),
    path('release/<int:pk>/update/', v.release_update, name='release_update'),
    path('release/<int:pk>/delete/', v.release_delete, name='release_delete'),

    # Destination Category -----------------------------------------------------
    path('destination/category/', v.destcat_list, name='destcat_list'),
    path('destination/category/create/', v.destcat_create, name='destcat_create'),
    path('destination/category/<int:pk>/update/', v.destcat_update, name='destcat_update'),
    path('destination/category/<int:pk>/delete/', v.destcat_delete, name='destcat_delete'),

    # Destination ---------------------------------------------------------------
    path('destination/', v.destination_list, name='destination_list'),
    path('destination/create/', v.destination_create, name='destination_create'),
    path('destination/<int:pk>/update/', v.destination_update, name='destination_update'),
    path('destination/<int:pk>/delete/', v.destination_delete, name='destination_delete'),

    # FormPayment ---------------------------------------------------------------
    path('formpayment/', v.formpayment_list, name='formpayment_list'),
    path('formpayment/create/', v.formpayment_create, name='formpayment_create'),
    path('formpayment/<int:pk>/update/', v.formpayment_update, name='formpayment_update'),
    path('formpayment/<int:pk>/delete/', v.formpayment_delete, name='formpayment_delete'),

    # Payment -------------------------------------------------------------------
    path('payment/', v.payment_list, name='payment_list'),
    path('payment/create/', v.payment_create, name='payment_create'),
    path('payment/<int:pk>/details/', v.payment_details, name='payment_details'),
    path('payment/<int:pk>/update/', v.Payment_update, name='Payment_update'),
    path('payment/<int:pk>/delete/', v.payment_delete, name='payment_delete'),
]

order/urls.py
from django.urls import path

from . import views as v


app_name = "order"


urlpatterns = [
    # Order ---------------------------------------------------------------------
    path('', v.order_list, name='order_list'),
    path('create/', v.order_create, name='order_create'),
    path('<int:pk>/details/', v.order_details, name='order_details'),
    path('<int:pk>/update/', v.order_update, name='order_update'),
    path('<int:pk>/delete/', v.order_delete, name='order_delete'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('dashboard/', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),

    path('financial/', include('financial.urls'), name='financial'),
    path('order/', include('order.urls'), name='order'),
    path('product/', include('product.urls'), name='product'),
    path('register/', include('register.urls'), name='register')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

financial/models.py
from django.db import models
from django.urls.base import reverse_lazy as _

from order.models import Order



class Bank(models.Model):
    name = models.CharField( max_length=50)
    number = models.CharField(max_length=10)
    agency = models.CharField(max_length=8)
    details = models.CharField(max_length=255, null=True, blank=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Bank'
        verbose_name_plural = 'Banks'
        ordering = ['-createdin']

    def __str__(self):
        return self.name

    def bank_gau_detail(self):
        return _('financial:bank_details', args=[self.pk])

    def bank_gau_edit(self):
        return _('financial:bank_update', args=[self.pk])

    def bank_gau_delete(self):
        return _('financial:bank_delete', args=[self.pk])


class Account(models.Model):
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE, related_name='banks')
    name = models.CharField( max_length=50)
    description = models.CharField(max_length=100, blank=True)
    details = models.CharField(max_length=255, null=True, blank=True)
    balance = models.DecimalField(max_digits=12, decimal_places=2, default=0) 
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'
        ordering = ['-createdin']

    def __str__(self):
        return self.name

    # def account_gau_detail(self):
    #     return _('financial:account_details', args=[{'bank_id': self.bank_id},{'pk':self.pk}])

    # def account_gau_edit(self):
    #     return _('financial:account_update', args=[self.pk])

    # def account_gau_delete(self):
    #     return _('financial:account_delete', args=[{'bank_id': self.bank_id},{'pk':self.pk}])


class DestinationCategory(models.Model):
    name = models.CharField(max_length=50)
    details = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.name)

    def destcat_gau_edit(self):
        return _('financial:destcat_update', args=[self.pk])

    def destcat_gau_delete(self):
        return _('financial:destcat_delete', args=[self.pk])

class Destination(models.Model):
    name = models.CharField( max_length=50)
    category = models.ForeignKey(DestinationCategory, on_delete=models.CASCADE)
    details = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.name)

    def dest_gau_edit(self):
        return _('financial:destination_update', args=[self.pk])

    def dest_gau_delete(self):
        return _('financial:destination_delete', args=[self.pk])

class Release(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order')
    date = models.DateField()
    description = models.CharField(max_length=100, blank=True)
    valueorder = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    installments = models.CharField(max_length=2, blank=True)
    totalorder = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    details = models.CharField(max_length=255, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.order)

    def release_gau_edit(self):
        return _('financial:release_update', args=[self.pk])

    def release_gau_delete(self):
        return _('financial:release_delete', args=[self.pk])

    class Meta:
        ordering = ['-createdin']


class FormPayment(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Form Payment'
        verbose_name_plural = 'Forms Payments'

    def __str__(self):
        return self.name

    def formpayment_gau_edit(self):
        return _('financial:Payment_update', args=[self.pk])

    def formpayment_gau_delete(self):
        return _('financial:payment_delete', args=[self.pk])


class Payment(models.Model):
    release = models.ForeignKey(Release, on_delete=models.CASCADE, related_name='release')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='account')
    date = models.DateField()
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, null=True, blank=True)
    value = models.DecimalField(max_digits=11, decimal_places=2)
    details = models.CharField(max_length=255, null=True, blank=True)
    formpayment = models.ForeignKey(FormPayment, on_delete=models.CASCADE, max_length=255)
    updated = models.DateTimeField(auto_now=True)
    createdin = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'
        ordering = ['-createdin']

    def __str__(self):
        return self.name

    def payment_gau_detail(self):
        return _('financial:payment_details', args=[self.pk])

    def payment_gau_edit(self):
        return _('financial:Payment_update', args=[self.pk])

    def payment_gau_delete(self):
        return _('financial:payment_delete', args=[self.pk])

financial/forms.py
from django import forms

from .models import Account


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = '__all__'
        exclude = ('bank',)

financial/templates/financial/payment/paymentCreateUpdate.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Payment{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Payment</h5>
        <form class="form-horizontal" action="" method="POST" enctype="">
          {% csrf_token %}
          <div class="row">
            <div class="col-6 col-lg-3">
              <label for="id_date" class="col-form-label">Date</label>
              {{ form.date }}
            </div>
            <div class="col-3 col-lg-3">
              <label for="id_release" class="col-form-label">Release</label>
              <select class="form-select" name="release" id="id_release">
                {% for item in form.release %}
                <option>{{ item }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-3 col-lg-3">
              <label for="id_account" class="col-form-label">Account</label>
              <select class="form-select" name="account" id="id_account">
                {% for item in form.account %}
                <option>{{ item }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-3 col-lg-3">
              <label for="id_destination" class="col-form-label">Destination</label>
              <select class="form-select" name="account" id="id_destination">
                {% for item in form.destination %}
                <option>{{ item }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="row">
            <div class="col-6 col-lg-3">
              <label for="id_value" class="col-form-label">Value</label>
              {{ form.value }}
            </div>
            <div class="col-6 col-lg-3">
              <label for="id_formpayment" class="col-form-label">Formpayment</label>
              <select class="form-select" name="account" id="id_formpayment">
                {% for item in form.formpayment %}
                <option>{{ item }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-4 col-lg-6">
              <label for="id_details" class="col-form-label">Details</label>
              {{ form.details }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-lg-12">
              <label for="id_description" class="col-form-label">Description</label>
              {{ form.description }}
            </div>
          </div>
          <div class="row my-3">
            <div class="col-sm-12">
              <button type="submit" class="btn btn-primary btn-sm" value="Update">Submit</button>
              <a class="btn btn-danger btn-sm" href="{% url 'financial:payment_list' %}">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

financial/templates/financial/payment/paymentDelete.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Delete{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <h5>Delete</h5>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Are you sure you want to delete the record: <b>{{ object.name }}</b>?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-sm">Submit</button>
          <a class="btn btn-danger btn-sm" href="{% url 'financial:payment_list' %}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</main>
{% endblock %}

financial/templates/financial/payment/paymentDetails.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Details{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Payment Details</h5>
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button"
            role="tab" aria-controls="profile" aria-selected="true">Profile</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button"
            role="tab" aria-controls="contact" aria-selected="false" tabindex="-1">Contact</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="adress-tab" data-bs-toggle="tab" data-bs-target="#adress" type="button"
            role="tab" aria-controls="adress" aria-selected="false" tabindex="-1">Adress</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="orders-tab" data-bs-toggle="tab" data-bs-target="#orders" type="button"
            role="tab" aria-controls="orders" aria-selected="false" tabindex="-1">Orders</button>
        </li>
      </ul>
      <div class="tab-content pt-4" id="myTabContent">
        <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          <div class="card mb-1 p-3">
            <p><b>Release: </b> {{ object.release }}</p>
            <p><b>Account: </b> {{ object.account }}</p>
            <p><b>Date: </b> {{ object.date }}</p>
          </div>
        </div>
        <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
          <div class="card mb-1 p-3">
            <p><b>Destination: </b> {{ object.destination }}</p>
            <p><b>Description: </b> {{ object.description }}</p>
            <p><b>Details: </b> {{ object.details }}</p>
          </div>
        </div>
        <div class="tab-pane fade" id="adress" role="tabpanel" aria-labelledby="adress-tab">
          <div class="card mb-1 p-3">
            <p><b>value: </b> {{ object.value }}</p>
            <p><b>Formpayment: </b> {{ object.formpayment }}</p>
          </div>
        </div>
        <div class="tab-pane fade" id="orders" role="tabpanel" aria-labelledby="orders-tab">
          <div class="card mb-1 p-3">
            <p class="">
              Saepe animi et soluta ad odit soluta sunt. Nihil quos omnis animi debitis cumque. Accusantium quibusdam
              perspiciatis qui qui omnis magnam. Officiis accusamus impedit molestias nostrum veniam. Qui amet ipsum
              iure.
              Dignissimos fuga tempore dolor.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

financial/templates/financial/payment/paymentList.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Payments{% endblock %}

{% block dashboard %}
<main id="main" class="main">
  <div class="row align-items-center pb-2">
    <div class="col-6">
      <h5 class="">Payments</h5>
    </div>
    <div class="col-6">
      <a class="d-flex float-end" href="{% url 'financial:payment_create' %}">
        <img src="{% static 'img/plus.png' %}" alt="" width="40" height="40">
      </a>
    </div>
  </div>

  <table class="table table-sm" id="id_table">
    <caption>Payments</caption>
    <thead>
      <tr>
        <th scope="col">Release</th>
        <th scope="col">Account</th>
        <th scope="col">Date</th>
        <th scope="col">Destination</th>
        <th scope="col">Description</th>
        <th scope="col">Value</th>
        <th scope="col">Details</th>
        <th scope="col">Formpayment</th>
        <th scope="col">Edit/Del</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr>
        <td>
          <a href="{{ object.payment_gau_detail }}">{{ object.release }}</a>
        </td>
        <td>{{ object.account }}</td>
        <td>{{ object.date }}</td>
        <td>{{ object.destination }}</td>
        <td>{{ object.description }}</td>
        <td>{{ object.value }}</td>
        <td>{{ object.details }}</td>
        <td>{{ object.formpayment }}</td>
        <a class="px-2" href="{{ object.payment_gau_edit }}">
          <i class="fa fa-edit"></i>
        </a>
        <a class="px-2" href="{{ object.payment_gau_delete }}" style="padding-left: 7px">
          <i class="fa fa-close no"></i>
        </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock dashboard %}